let allOrders=[], currentOrder=null, completedImageData="";
async function getAll(){const r=await fetch("/api/admin/orders",{cache:"no-store"});if(!r.ok)throw new Error("관리자 주문 조회 실패");return await r.json()}
async function putOrder(order){const r=await fetch("/api/admin/orders/"+encodeURIComponent(order.storageId),{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(order)});if(!r.ok)throw new Error("주문 저장 실패");return await r.json()}
async function deleteOrder(id){const r=await fetch("/api/admin/orders/"+encodeURIComponent(id),{method:"DELETE"});if(!r.ok)throw new Error("주문 삭제 실패")}
const esc=s=>String(s??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const money=n=>(Number(n)||0).toLocaleString("ko-KR")+"원";
function initialAdmin(o){return {...o,status:o.status||"신규 접수",paymentStatus:o.paymentStatus||"미입금",basePrice:Number(o.basePrice)||estimateBasePrice(o),receivedAmount:Number(o.receivedAmount)||0,extraAmount:Number(o.extraAmount)||0,completedDate:o.completedDate||"",trackingNumber:o.trackingNumber||"",customerReview:o.customerReview||"",adminMemo:o.adminMemo||"",customerVisible:Boolean(o.customerVisible),customerMessage:o.customerMessage||"",publicWork:Boolean(o.publicWork),completedImage:o.completedImage||""}}
function estimateBasePrice(o){const count=Number(o.sentenceCharacterCount)||String(o.sentence||"").replace(/\s/g,"").length;let p=count>=100?50000:count>=60?30000:count>=30?20000:10000;const s=o.workSize||"";let sp=s.includes("신문지 한 면보다 큰")?50000:s.includes("절반 초과")?30000:s.includes("A4 ~")?20000:10000;return Math.max(p,sp)}
async function load(){allOrders=(await getAll()).map(initialAdmin);render()}
function render(){const q=document.querySelector("#searchInput").value.trim().toLowerCase(), status=document.querySelector("#statusFilter").value, pay=document.querySelector("#paymentFilter").value;const rows=allOrders.filter(o=>{const text=[o.id,o.name,o.phone,o.workType,o.recipient,o.sentence].join(" ").toLowerCase();return(!q||text.includes(q))&&(!status||o.status===status)&&(!pay||o.paymentStatus===pay)});document.querySelector("#resultCount").textContent=rows.length+"건";document.querySelector("#orderList").innerHTML=rows.length?rows.map(orderCard).join(""):'<div class="empty-state">조건에 맞는 주문이 없습니다.</div>';dashboard()}
function orderCard(o){return `<article class="order-card" data-id="${o.storageId}"><div class="order-number">${esc(o.id||("주문 "+o.storageId))}</div><div class="order-main"><strong>${esc(o.name||"이름 없음")}</strong><small>${esc(o.phone||"")}</small></div><div class="order-sub"><strong>${esc(o.workType||"종류 미입력")}</strong><small>${esc(o.createdAt||"")}</small></div><div><span class="status-badge">${esc(o.status)}</span></div><div class="order-price">${money(o.receivedAmount+o.extraAmount||o.basePrice)}</div><div>›</div></article>`}
function dashboard(){const c=s=>allOrders.filter(o=>o.status===s).length;document.querySelector("#countAll").textContent=allOrders.length;document.querySelector("#countNew").textContent=c("신규 접수");document.querySelector("#countMaking").textContent=c("제작 중");document.querySelector("#countDone").textContent=c("발송 완료");document.querySelector("#countUnpaid").textContent=allOrders.filter(o=>o.paymentStatus!=="입금 완료").length;document.querySelector("#totalRevenue").textContent=money(allOrders.reduce((s,o)=>s+(Number(o.receivedAmount)||0)+(Number(o.extraAmount)||0),0))}
function openDetail(id){currentOrder=allOrders.find(o=>o.storageId===Number(id));if(!currentOrder)return;completedImageData=currentOrder.completedImage||"";document.querySelector("#storageId").value=currentOrder.storageId;document.querySelector("#modalTitle").textContent=(currentOrder.name||"고객")+"님의 주문";document.querySelector("#customerSummary").innerHTML=`<strong>${esc(currentOrder.id||"")}</strong><br>${esc(currentOrder.createdAt||"")} · ${esc(currentOrder.phone||"")} · ${esc(currentOrder.email||"")}<br>${esc(currentOrder.workType||"")} / ${esc(currentOrder.workSize||"크기 미정")} / 희망일 ${esc(currentOrder.dueDate||"미정")}`;set("adminStatus",currentOrder.status);set("adminPayment",currentOrder.paymentStatus);set("adminBasePrice",currentOrder.basePrice);set("adminReceivedAmount",currentOrder.receivedAmount);set("adminExtraAmount",currentOrder.extraAmount);set("adminCompletedDate",currentOrder.completedDate);set("adminTrackingNumber",currentOrder.trackingNumber);set("adminReview",currentOrder.customerReview);set("adminMemo",currentOrder.adminMemo);set("adminCustomerMessage",currentOrder.customerMessage);document.querySelector("#adminCustomerVisible").checked=currentOrder.customerVisible;document.querySelector("#adminPublic").checked=currentOrder.publicWork;document.querySelector("#referenceImages").innerHTML=imageHtml([currentOrder.referenceImage1,currentOrder.referenceImage2]);document.querySelector("#completedImagePreview").innerHTML=imageHtml([completedImageData]);document.querySelector("#requestText").innerHTML=`<h3>전하고 싶은 마음과 사연</h3><p>${esc(currentOrder.story||"없음")}</p><h3>최종 문구</h3><p>${esc(currentOrder.sentence||"함께 상의")}</p><h3>추가 요청</h3><p>${esc(currentOrder.extra||"없음")}</p>`;document.querySelector("#detailModal").hidden=false;document.body.style.overflow="hidden"}
function imageHtml(arr){const imgs=arr.filter(Boolean);return imgs.length?imgs.map(src=>`<img src="${src}" alt="이미지">`).join(""):'<div class="no-image">등록된 이미지가 없습니다.</div>'}
function set(id,v){document.getElementById(id).value=v??""}
function closeDetail(){document.querySelector("#detailModal").hidden=true;document.body.style.overflow="";currentOrder=null}
async function saveAdmin(e){e.preventDefault();if(!currentOrder)return;Object.assign(currentOrder,{status:val("adminStatus"),paymentStatus:val("adminPayment"),basePrice:Number(val("adminBasePrice"))||0,receivedAmount:Number(val("adminReceivedAmount"))||0,extraAmount:Number(val("adminExtraAmount"))||0,completedDate:val("adminCompletedDate"),trackingNumber:val("adminTrackingNumber"),customerReview:val("adminReview"),adminMemo:val("adminMemo"),customerVisible:document.querySelector("#adminCustomerVisible").checked,customerMessage:val("adminCustomerMessage"),publicWork:document.querySelector("#adminPublic").checked,completedImage:completedImageData,updatedAt:new Date().toLocaleString("ko-KR")});await putOrder(currentOrder);await load();closeDetail();alert("변경 내용을 저장했습니다.")}
const val=id=>document.getElementById(id).value.trim();
function readCompletedImage(input){const f=input.files&&input.files[0];if(!f)return;if(!f.type.startsWith("image/")){alert("이미지 파일만 선택해 주세요.");return}const r=new FileReader();r.onload=e=>{completedImageData=e.target.result;document.querySelector("#completedImagePreview").innerHTML=imageHtml([completedImageData])};r.readAsDataURL(f)}
async function removeCurrent(){if(!currentOrder||!confirm("이 주문을 삭제할까요? 삭제 후에는 되돌릴 수 없습니다."))return;await deleteOrder(currentOrder.storageId);await load();closeDetail()}
function backup(){const blob=new Blob([JSON.stringify(allOrders,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="글결_주문백업_"+new Date().toISOString().slice(0,10)+".json";a.click();URL.revokeObjectURL(a.href)}
function restore(input){const f=input.files&&input.files[0];if(!f)return;const r=new FileReader();r.onload=async e=>{try{const rows=JSON.parse(e.target.result);if(!Array.isArray(rows))throw new Error();if(!confirm(rows.length+"건의 자료를 서버에 복원할까요? 같은 주문은 덮어쓸 수 있습니다."))return;const resp=await fetch("/api/admin/import",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({orders:rows.map(initialAdmin)})});if(!resp.ok)throw new Error();await load();alert("자료를 복원했습니다.")}catch{alert("복원에 실패했습니다. 올바른 글결 백업 파일인지 확인해 주세요.")}input.value=""};r.readAsText(f)}
function printCurrent(){if(!currentOrder)return;const w=window.open("","_blank","width=900,height=800");w.document.write(`<html><head><title>글결 작업 의뢰서</title><style>@page{size:A4;margin:18mm}body{font-family:Malgun Gothic,sans-serif;color:#222}h1{border-bottom:2px solid #333;padding-bottom:12px}.grid{display:grid;grid-template-columns:1fr 1fr;border-top:1px solid #777;border-left:1px solid #777}.grid div{padding:9px;border-right:1px solid #777;border-bottom:1px solid #777}.box{margin-top:14px;border:1px solid #777;padding:12px;white-space:pre-wrap}.images{display:flex;gap:10px;margin-top:12px}.images img{max-width:48%;max-height:220px;object-fit:contain}</style></head><body><h1>글결 작업 의뢰서</h1><div class="grid"><div>주문번호: ${esc(currentOrder.id)}</div><div>작성일: ${esc(currentOrder.createdAt)}</div><div>성함: ${esc(currentOrder.name)}</div><div>연락처: ${esc(currentOrder.phone)}</div><div>작품 종류: ${esc(currentOrder.workType)}</div><div>희망 크기: ${esc(currentOrder.workSize||"함께 상의")}</div><div>진행 상태: ${esc(currentOrder.status)}</div><div>기본비용: ${money(currentOrder.basePrice)}</div></div><div class="box"><b>전하고 싶은 마음과 사연</b><br><br>${esc(currentOrder.story||"")}</div><div class="box"><b>최종 문구</b><br><br>${esc(currentOrder.sentence||"함께 상의")}</div><div class="images">${[currentOrder.referenceImage1,currentOrder.referenceImage2].filter(Boolean).map(x=>`<img src="${x}">`).join("")}</div><script>window.onload=()=>setTimeout(()=>window.print(),300)<\/script></body></html>`);w.document.close()}
document.addEventListener("DOMContentLoaded",()=>{load().catch(()=>alert("주문 자료를 불러오지 못했습니다. 홈페이지와 같은 방식으로 실행해 주세요."));["searchInput","statusFilter","paymentFilter"].forEach(id=>document.getElementById(id).addEventListener(id==="searchInput"?"input":"change",render));document.querySelector("#orderList").addEventListener("click",e=>{const c=e.target.closest(".order-card");if(c)openDetail(c.dataset.id)});document.querySelectorAll("[data-close]").forEach(x=>x.addEventListener("click",closeDetail));document.querySelector("#adminForm").addEventListener("submit",saveAdmin);document.querySelector("#completedImageInput").addEventListener("change",e=>readCompletedImage(e.target));document.querySelector("#deleteButton").addEventListener("click",removeCurrent);document.querySelector("#backupButton").addEventListener("click",backup);document.querySelector("#restoreInput").addEventListener("change",e=>restore(e.target));document.querySelector("#printButton").addEventListener("click",printCurrent);document.addEventListener("keydown",e=>{if(e.key==="Escape")closeDetail()})});
